### ISSUE TITLE
ColorVariable linter does not report error.

### ISSUE THREAD

**Issue by makotot** [causes/scss-lint#365]
scss-lint(version: 0.33.0) does not report error, though `#ff0` is not in variable declaration.

In .scss-lint.yml
```yml
  ColorVariable:
    enabled: true
```

my test.scss is below.
```scss
.color-variable {
  color: #ff0;
}
```
