### ISSUE TITLE
Error while linting

### ISSUE THREAD

**Issue by albertorestifo** [causes/scss-lint#366]
I got this error on the console:

```
DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: foo bar:has(baz)

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: foo.x bar.y:has(baz.z)

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: .foo:has(.bar)

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: .bip .bap

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: .bip:has(.bap)

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: x:has(.bar)

DEPRECATION WARNING on line 1, column 1:
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
For example: y:has(.bap)

SCSSLint::Linter::BangFormat raised unexpected error linting file node_modules/gulp-sass/node_modules/node-sass/test/fixtures/spec/spec/libsass-todo-tests/libsass/lists/input.scss: '[BUG] Unknown operator nil'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/script/parser.rb:206:in `precedence_of'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/script/tree/list_literal.rb:33:in `block in to_sass'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/script/tree/list_literal.rb:32:in `map'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/script/tree/list_literal.rb:32:in `to_sass'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/prop_node.rb:132:in `val_to_sass'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/prop_node.rb:109:in `declaration'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/convert.rb:233:in `visit_prop'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:36:in `visit'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/convert.rb:10:in `visit'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/node.rb:201:in `to_sass'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter/bang_format.rb:9:in `visit_prop'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:36:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:127:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:138:in `block in visit_children'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:136:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:136:in `visit_children'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:38:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:127:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:138:in `block in visit_children'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:136:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:136:in `visit_children'
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:38:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:127:in `visit'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/linter.rb:21:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:58:in `run_linter'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:39:in `block in find_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:37:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:37:in `find_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:21:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:20:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/runner.rb:20:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:52:in `scan_for_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:46:in `act_on_options'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:25:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.33.0/bin/scss-lint:6:in `<top (required)>'
/usr/bin/scss-lint:23:in `load'
/usr/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/causes/scss-lint/issues
```

This is my `.scss-lint.yml` file:
```yaml
scss_files: "public/style/scss/**/*.scss"

linters:
  BorderZero:
    enabled: true
    convention: 0

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true

  Indentation:
    enabled: true

  LeadingZero:
    enabled: true

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false

  NestingDepth:
    enabled: true
    max_depth: 2

  PropertySpelling:
    enabled: true
    extra_properties:
      - will-change

  QualifyingElement:
    enabled: true

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true

  StringQuotes:
    enabled: true

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
      - box-shadow
      - border

  VendorPrefixes:
    enabled: true

  ZeroUnit:
    enabled: true

```

It took about 30 seconds for the error to appear, and it was the first and only output I received.

OSX 10.10.2, Ruby 2.0.0p481
