### ISSUE TITLE
Disable linters for a @mixin

### ISSUE THREAD

**Issue by abpetkov** [causes/scss-lint#369]
Disabling a linter for an ordinary selector works perfect (any example you've given in the Readme). But when it comes to disabling a linter for a mixin, it doesn't seem to work for me. I have this mixin:

```scss
@mixin font-size($size, $line: $size * 1.5) {
  font-size: ($size * 10) + px;
  line-height: ($line * 10) + px;
  font-size: $size + rem;
  line-height: $line + rem;
}
```

In this case I need the fallback px values for IE support and can't remove them. So I'm trying to add the `// scss-lint:disable DuplicateProperty` comment to avoid the duplicated property warning. Tried both within the mixin on the first line and outside right before it. Both didn't work.

Is there a different way to do this (without excluding the whole file where the mixin is) or not working for a reason?

**Comment by sds** [comment]
Duplicate of #355.

**Comment by abpetkov** [comment]
@sds, I don't see how this is a duplicate of the issue you linked. The issue there seems to be the include itself, rather than the mixin. I'm still seeing the warning and I'm using the latest release of scss-lint (0.34.0). Here's a more detailed example:

```scss
// _font-size.scss

// scss-lint:disable DuplicateProperty
@mixin font-size($size, $line: $size * 1.5) {
  font-size: ($size * 10) + px;
  line-height: ($line * 10) + px;
  font-size: $size + rem;
  line-height: $line + rem;
}
```

Just one usage of the mixin out of many.

```scss
// _main.scss

body {
  @include font-size(1.6, 2.4);
}
```

Getting the warning in the mixin file, not where it's being included:

```shell
app/assets/stylesheets/helpers/_font-size.scss:9 [W] DuplicateProperty: Property `font-size` already defined on line 7
app/assets/stylesheets/helpers/_font-size.scss:10 [W] DuplicateProperty: Property `line-height` already defined on line 8
```

Please let me know if you can reproduce that.
