### ISSUE TITLE
Use `transparent` as a ColorVariable?

### ISSUE THREAD

**Issue by chris-dura** [causes/scss-lint#376]
```scss
.widget {
   border: 4px solid transparent;
}
```
throws this error:
```bash
[W] ColorVariable: Color literals like `transparent` should only be used in variable declarations; they should be referred to via variable everywhere else.
```
I guess I understand the "why"... I would certainly want to avoid using other `ColorKeywords` like `red` or `green`.

To get around this, I guess I have to write:
```scss

$transparent: transparent;
...

.widget {
   border: 4px solid $transparent;
}
```

Writing `$transparent: transparent;` seems a little overwrought to me, so just wondering if this is the expected solution, or should `transparent` be an exception to the Linter?
