### ISSUE TITLE
I don't understand how to exclude identifiers in the VendorPrefixes rule

### ISSUE THREAD

**Issue by himedlooff** [causes/scss-lint#379]
Here's my config:

```yml
  VendorPrefixes:
    enabled: true
    severity: warning
    identifier_list: base
    include: []
    exclude:
      - keyframes
```

Here's the SCSS:

```scss
@-webkit-keyframes anim {
    0% { opacity: 0; }
}
```

But I'm still getting the following linting error: "Avoid vendor prefixes."
